### ISSUE TITLE
First use the method "opensearch" the SearchView’s animation don't work

### ISSUE THREAD

**Issue by BigSeer** [Mauker1/MaterialSearchView#79] opened 2017-01-16 03:11 UTC
My English bad, if you don‘t understand what i mean，i can e-mail the video of henomenon to you。
version 5.1

**Comment by Mauker1** [comment] 2017-01-17 16:04
The video will help. You can upload it and post a link here.

**Comment by BigSeer** [comment] 2017-01-18 07:50
look this [http://v.youku.com/v_show/id_XMjQ3NTcxMTc4MA==.html](url)

**Comment by BigSeer** [comment] 2017-01-18 07:51
Look this http://v.youku.com/v_show/id_XMjQ3NTcxMTc4MA==.html

**Comment by Mauker1** [comment] 2017-01-23 22:12
I couldn't see the video, can you upload it somewhere else?

**Comment by MattWilliams89** [comment] 2017-01-31 21:38
I'm seeing this too. Demoable in the sample app. FIrst time the searchview is opened, the circular reveal animation does not work

**Comment by Mauker1** [comment] 2017-01-31 21:42
Now I understand what the problem is, thanks 👍 
What's your device and OS version?

**Comment by MattWilliams89** [comment] 2017-01-31 21:50
I'm on Nexus 6P and Android 7.1.1.

Thanks 😄

**Comment by westlinkin** [comment] 2017-03-06 14:17
same here. Nexus 5 with os version 6.0.1

**Comment by creati8e** [comment] 2017-04-05 11:21
is this bug fixed in 1.2.2?

**Comment by leoemili** [comment] 2018-07-17 09:40
same here. Xiaomi mi 5 API 24. Android 7.0

**Comment by Mauker1** [comment] 2021-02-09 05:50
Made the view `INVISIBLE` instead of `GONE`. It seems to be working on the devices I tested. If this still happens after 2.0.0-beta01 please feel free to open a new issue.

**Closed by Mauker1** 2021-02-09 05:50 UTC
Labels: bug
